name = "barona-mobile-detailing"
main = "worker.js"
compatibility_date = "2026-08-19"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "barona-bookings"
database_id = "08cd47e8-ec98-4a27-9389-376f5404d2a1"
